version: '3.8'

services:
  mysql:
    image: mysql:8.0.19
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  keycloak:
    image: brasatech/keycloak:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=token-exchange,docker,web-authn
      - KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/conf/truststore.p12
      - KC_HTTPS_TRUST_STORE_TYPE=PKCS12
      - KC_HTTPS_TRUST_STORE_PASSWORD=changeit
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/brasatech-server.p12
      - KC_HTTPS_KEY_STORE_TYPE=PKCS12
      - KC_HTTPS_KEY_STORE_PASSWORD=changeit
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=9443
      - KC_DB_URL_HOST=mysql
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - 9443:8443
    depends_on:
        - mysql

volumes:
  mysql_data:
    name: mysql_data
